
name: Spring Boot CI with Maven

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches:
      - "**"
    paths:
      - "**"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: init-checkout
        uses: actions/checkout@v3
      - name: init-java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: init-maven
        uses: maven/maven-build-action@v2
        with:
          maven-version: current
      - name: build-vault-boot
        run: |
          mvn -Denv.scp=vault -DskipTests --batch-mode --update-snapshots package
      - name: build-aws-boot
        run: |
          mvn -Denv.scp=aws -DskipTests --batch-mode --update-snapshots package
      - name: build-gcp-boot
        run: |
          mvn -Denv.scp=gcp -DskipTests --batch-mode --update-snapshots package
      - name: build-azure-boot
        run: |
          mvn -Denv.scp=azure -DskipTests --batch-mode --update-snapshots package
